### ISSUE TITLE
RaindropsOnGlass at night are black

### ISSUE THREAD

**Issue by mike-rowley** [YHK-UEPlugins-Public/017_RaindropsOnGlass_Public#1]
I am trying to apply Type D Raindrops on a Plane and they appear as black at night.  How do I make them semi opaque at night?  

I purchased the asset pack but cannot make them work at night, this is completely unusable to me if it only works in daylight.

**Comment by yehaike** [comment]
Hi, Also replied to you in the UE Marketplace.
Thank you for reaching out and sharing your concerns about the Type D asset. I understand that you’re experiencing issues with the visibility of raindrops on a plane in a night scene, where they appear black and are not rendering as expected. 
Could you please send me your night scene test project? I will help you test and address the issue. 
Also, you can add me on Discord: YeHaike.

**Comment by yehaike** [comment]
Hi, mike-rowley
As I replied to you in Discord. You can adjust the brightness of the raindrops through the “RaindropsColorScale” Material property, as detailed in the documentation below. If you have any further questions, please feel free to contact me.
[https://github.com/YHK-UEPlugins-Public/017_RaindropsOnGlass_Public?tab=readme-ov-file#1-raindrop-brightness-control-by-default-the-typed-or-typee-glass-raindrop-material-employs-surface-forwardshading-lightmode-which-can-cause-raindrops-to-appear-darker-in-certain-scenarios-such-as-scenes-without-lighting-eg-night-scenes](https://github.com/YHK-UEPlugins-Public/017_RaindropsOnGlass_Public?tab=readme-ov-file#1-raindrop-brightness-control-by-default-the-typed-or-typee-glass-raindrop-material-employs-surface-forwardshading-lightmode-which-can-cause-raindrops-to-appear-darker-in-certain-scenarios-such-as-scenes-without-lighting-eg-night-scenes)
Thank you very much.

**Comment by yehaike** [comment]
I have just added a new “Solution 02,” which I recommend using. It is also included in the document.
![image](https://github.com/YHK-UEPlugins-Public/017_RaindropsOnGlass_Public/assets/10463421/ab895be2-c688-49ce-b7c2-32cbc5e7483f)
